package Models;
// Generated 19 ene. 2020 23:54:08 by Hibernate Tools 4.3.1

/**
 * Purificador generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int id;
     private String material;
     private String modelo;
     private String nombre;
     private int precio;
     private Boolean disponible;

    public Equipo(int id, String material, String modelo, String nombre, int precio, Boolean disponible) {
        this.id = id;
        this.material = material;
        this.modelo = modelo;
        this.nombre = nombre;
        this.precio = precio;
        this.disponible = disponible;
    }

    public Equipo(String material, String modelo, String nombre, int precio) {
        this.material = material;
        this.modelo = modelo;
        this.nombre = nombre;
        this.precio = precio;
        this.disponible=true;
    }

 

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getPrecio() {
        return precio;
    }

    public void setPrecio(int precio) {
        this.precio = precio;
    }

    public Boolean getDisponible() {
        return disponible;
    }

    public void setDisponible(Boolean disponible) {
        this.disponible = disponible;
    }

   

  



}


