package Models;
// Generated 8 feb. 2020 0:48:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EquipoCliente generated by hbm2java
 */
public class EquipoCliente  implements java.io.Serializable {


     private int id;
     private int idCliente;
     private Cliente cliente;
     private int idEquipo;
     private Equipo equipo;
     private Date fechaCreado;

    public EquipoCliente() {
    }

    public EquipoCliente(Cliente cliente, Equipo equipo) {
        this.id=0;
        this.cliente = cliente;
        this.equipo = equipo;
        this.idCliente=cliente.getId();
        this.idEquipo=equipo.getId();
    }

    public EquipoCliente(int id, int idCliente, int idEquipo) {
        this.id = id;
        this.idCliente = idCliente;
        this.idEquipo = idEquipo;
    }
    
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Integer getIdPur() {
        return idEquipo;
    }

    public void setIdPur(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }

    public Equipo getEquipo() {
        return equipo;
    }

    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

    public Date getFechaCreado() {
        return fechaCreado;
    }

    public void setFechaCreado(Date fechaCreado) {
        this.fechaCreado = fechaCreado;
    }

    public int getIdCliente() {
        return idCliente;
    }

   

   
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public int getIdEquipo() {
        return idEquipo;
    }

    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }

    
    
    
   




}


