package Models;
// Generated 19 ene. 2020 23:54:08 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import logica.Config;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento implements java.io.Serializable {

    private int id;
    private Cliente cliente;
    private Tecnico tecnico;
    private int idOrden;
    private Integer diasPost;
    private String nota;
    private Integer costoServicioTecnico;
    private Integer valorMantenimiento;
    private int valorTotal;
    private Date fechaMan;
    private ArrayList<MantenimientoEquipo> mantenimientoEquipo = new ArrayList<MantenimientoEquipo>(0);

    public Mantenimiento(Cliente cliente) {
        this.cliente = cliente;
        this.costoServicioTecnico = 0;
        this.valorMantenimiento = 0;
    }

    public Mantenimiento(int id, Cliente cliente, Tecnico tecnico, int idOrden, Integer diasPost, String nota, Integer costoServicioTecnico, Integer valorMantenimiento, Date fechaMan) {
        this.id = id;
        this.cliente = cliente;
        this.tecnico = tecnico;
        this.idOrden = idOrden;
        this.diasPost = diasPost;
        this.nota = nota;
        this.costoServicioTecnico = costoServicioTecnico;
        this.valorMantenimiento = valorMantenimiento;

        this.fechaMan = fechaMan;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Tecnico getTecnico() {
        return tecnico;
    }

    public void setTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }

    public int getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(int idOrden) {
        this.idOrden = idOrden;
    }

    public Integer getDiasPost() {
        return diasPost;
    }

    public void setDiasPost(Integer diasPost) {
        this.diasPost = diasPost;
    }

    public String getNota() {
        return nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    public Integer getCostoServicioTecnico() {
        return costoServicioTecnico;
    }

    public void setCostoServicioTecnico(Integer costoServicioTecnico) {
        this.costoServicioTecnico = costoServicioTecnico;

    }

    public Integer getValorMantenimiento() {
        return valorMantenimiento;
    }

    public void setValorMantenimiento(Integer valorMantenimiento) {
        this.valorTotal = Config.getCostoMante() * mantenimientoEquipo.size() + valorMantenimiento;
        this.valorMantenimiento = valorMantenimiento;
    }

    public Date getFechaMan() {
        return fechaMan;
    }

    public void setFechaMan(Date fechaMan) {
        this.fechaMan = fechaMan;
    }

    public ArrayList<MantenimientoEquipo> getMantenimientoEquipo() {
        return mantenimientoEquipo;
    }

    public int getValorTotal() {
        return valorTotal;
    }

    
    public void agregarMantenimientoEquipo(MantenimientoEquipo mantEquipo) {
        this.mantenimientoEquipo.add(mantEquipo);
        this.costoServicioTecnico = Config.getCostoMante() * mantenimientoEquipo.size();
        this.valorTotal = Config.getCostoMante() * mantenimientoEquipo.size() + this.getValorMantenimiento();

    }

    public void setMantenimientoEquipo(ArrayList<MantenimientoEquipo> mantenimientoEquipo) {
        this.mantenimientoEquipo = mantenimientoEquipo;
    }

}
