package Models;
// Generated 19 ene. 2020 23:54:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import logica.Config;

/**
 * Repuesto generated by hbm2java
 */
public class Repuesto  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String tipo;
     private int valorCosto;
     private int valorVenta;
     private int iva;
     private int valorVentaIva;
     private int tipo_id;
     private Set<RepuestoMante> repuestoHasMantenimientos = new HashSet<RepuestoMante>(0);

    public Repuesto(int id, String nombre, String tipo, int valorCosto, int valorVenta, int iva, int valorVentaIva) {
        this.id = id;
        this.nombre = nombre;
        this.tipo = tipo;
        this.valorCosto = valorCosto;
        this.valorVenta = valorVenta;
        this.iva = iva;
        this.valorVentaIva = valorVentaIva;
    }

    public Repuesto(String nombre, int valorCosto, int valorVenta, int tipo_id) {
        this.nombre = nombre;
        this.valorCosto = valorCosto;
        this.valorVenta = valorVenta;
        this.tipo_id = tipo_id;
        this.iva= (int) (valorVenta * Config.getIva());
        this.valorVentaIva=this.iva+this.valorVenta;
        
    } 

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public int getValorCosto() {
        return valorCosto;
    }

    public void setValorCosto(int valorCosto) {
        this.valorCosto = valorCosto;
    }

    public int getValorVenta() {
        return valorVenta;
    }

    public void setValorVenta(int valorVenta) {
        this.valorVenta = valorVenta;
        this.setIva((int) (valorVenta * Config.getIva()));
        this.setValorVentaIva(this.iva+this.valorVenta);
        System.out.println(this.iva);
    }

    public int getIva() {
        return iva;
    }

    private void setIva(int iva) {
        this.iva = iva;
    }

    public int getValorVentaIva() {
        return valorVentaIva;
    }

    public void setValorVentaIva(int valorVentaIva) {
        this.valorVentaIva = valorVentaIva;
    }

    public int getTipo_id() {
        return tipo_id;
    }

    public void setTipo_id(int tipo_id) {
        this.tipo_id = tipo_id;
    }

    public Set<RepuestoMante> getRepuestoHasMantenimientos() {
        return repuestoHasMantenimientos;
    }

    public void setRepuestoHasMantenimientos(Set<RepuestoMante> repuestoHasMantenimientos) {
        this.repuestoHasMantenimientos = repuestoHasMantenimientos;
    }


     
}


