package Models;
// Generated 19 ene. 2020 23:54:08 by Hibernate Tools 4.3.1



/**
 * RepuestoHasMantenimiento generated by hbm2java
 */
public class RepuestoMante  implements java.io.Serializable {


     private int id;
     private MantenimientoEquipo mantenimientoEquipo;
     private int idManEqui;
     private Repuesto repuesto;
     private int idRepuesto;
     private Integer cantidadRep;
     private int costosRepuestos;
     private int ingresosRespuestos;

    public RepuestoMante(MantenimientoEquipo mantenimientoEquipo, Repuesto repuesto, Integer cantidadRep) {
        this.mantenimientoEquipo = mantenimientoEquipo;
        this.repuesto = repuesto;
        this.cantidadRep = cantidadRep;
        this.idManEqui=mantenimientoEquipo.getId();
        this.idRepuesto=repuesto.getId();
        this.costosRepuestos=cantidadRep*repuesto.getValorCosto();
        this.ingresosRespuestos=cantidadRep*repuesto.getValorVenta();
        
    }

   
    public int getId() {
        return this.id;
    }
    
    public void setId(int idRepMan) {
        this.id = idRepMan;
    }

    public int getIdManEqui() {
        return idManEqui;
    }
   
    

    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public Integer getCantidadRep() {
        return this.cantidadRep;
    }
    
    public void setCantidadRep(Integer cantidadRep) {
        this.cantidadRep = cantidadRep;
    }

    public int getIdRepuesto() {
        return idRepuesto;
    }

    public void setIdRepuesto(int idRepuesto) {
        this.idRepuesto = idRepuesto;
    }

    public Integer getCostosRepuestos() {
        return costosRepuestos;
    }

    public void setCostosRepuestos(Integer costosRepuestos) {
        this.costosRepuestos = costosRepuestos;
    }

    public Integer getIngresosRespuestos() {
        return ingresosRespuestos;
    }

    public void setIngresosRespuestos(Integer ingresosRespuestos) {
        this.ingresosRespuestos = ingresosRespuestos;
    }

 



}


