/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Equipo;

import Models.Equipo;
import View.Cliente.ClienteNuevo;
import View.Validaciones;
import control.EquipoController;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author blade
 */
public class EquipoEditar extends javax.swing.JInternalFrame {

    private static EquipoEditar equipoNuevo;
    private Equipo myEquipo;
   

    /**
     * Creates new form EquipoNuevo
     */
    private EquipoEditar(Equipo equipo) {
        this.myEquipo = equipo;
        initComponents();
        this.MostrarDatos();
        Validaciones.TextMayus(textModelo);
        Validaciones.TextMayus(textNombre);
        Validaciones.soloNumeros(textPrecio);
    }

    public static EquipoEditar getInstancia(Equipo equipo) {
        if (equipoNuevo == null) {
            return new EquipoEditar(equipo);
        }
        equipoNuevo.setEquipo(equipo);
        return equipoNuevo;
    }

   

   

    public void setEquipo(Equipo equipo) {
        this.myEquipo = equipo;
        this.MostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMaterial = new javax.swing.JComboBox<>();
        textModelo = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboDispo = new javax.swing.JComboBox<>();

        setTitle("EditarEquipo");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Material:");

        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setText("Modelo:");

        jLabel3.setFont(jLabel1.getFont());
        jLabel3.setText("Nombre:");

        jLabel4.setFont(jLabel1.getFont());
        jLabel4.setText("Precio:");

        comboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIDRIO", "METAL", "ACRILICO" }));

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(jLabel1.getFont());
        jLabel5.setText("Disponible:");

        comboDispo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "no diponible" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(textModelo)
                    .addComponent(comboMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboDispo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // T your handling code here:
        this.cerrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrar() {
        try {
            //this.dispose();        // TODO add your handling code here:

            this.setClosed(true);
            this.dispose();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ClienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // equipoControl.agregar();
        int resp = 0;
        myEquipo.setMaterial((String) this.getComboMaterial().getSelectedItem());

        myEquipo.setModelo(this.getTextModelo().getText());
        myEquipo.setNombre(this.getTextNombre().getText());
        myEquipo.setPrecio(Integer.parseInt(this.getTextPrecio().getText()));
        boolean dispo = this.getComboDispo().getSelectedIndex() == 0;
        myEquipo.setDisponible(dispo);
        if (EquipoController.getInstancia().editar(myEquipo)) {
            JOptionPane.showMessageDialog(null, "Se han registrado los cambios correctamente.");
            this.cerrar();
        } else {
            JOptionPane.showMessageDialog(this, "error a editar equipo", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public JComboBox<String> getComboMaterial() {
        return comboMaterial;
    }

    public JTextField getTextModelo() {
        return textModelo;
    }

    public JTextField getTextNombre() {
        return textNombre;
    }

    public JTextField getTextPrecio() {
        return textPrecio;
    }

    public JComboBox<String> getComboDispo() {
        return comboDispo;
    }

    public void setComboDispo(JComboBox<String> comboDispo) {
        this.comboDispo = comboDispo;
    }

    private void limpiar() {
        comboMaterial.setSelectedIndex(0);
        textModelo.setText("");
        textNombre.setText("");
        textPrecio.setText("");

    }

    private void MostrarDatos() {
        comboMaterial.setSelectedItem(this.myEquipo.getMaterial());
        textModelo.setText(this.myEquipo.getModelo());
        textNombre.setText(this.myEquipo.getNombre());
        textPrecio.setText(String.valueOf(this.myEquipo.getPrecio()));
        if (this.myEquipo.getDisponible()) {
            comboDispo.setSelectedIndex(0);
        } else {
            comboDispo.setSelectedIndex(1);
        }
    }

    public void keyTyped(KeyEvent e) {
        //se agrega funcion que obliga las letras en el textbox a ser mayusculas 
        char c = e.getKeyChar();
        //"e" es el nombre asignado al evento de tecla "c" representa a las letras
        if (Character.isLowerCase(c)) {
            String cad = ("" + c).toUpperCase();
            c = cad.charAt(0);
            e.setKeyChar(c);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDispo;
    private javax.swing.JComboBox<String> comboMaterial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
